language: c

os:
  - linux
  - osx

sudo: required
dist: trusty

compiler:
  - clang
  - gcc

matrix:
  fast_finish: true
  exclude:
    # Skip GCC builds on macOS.
    - os: osx
      compiler: gcc
  include:
    # Additional GCC builds for code coverage.
    - os: linux
      compiler: gcc
      env: CODE_COVERAGE=ON

cache:
  apt: true

addons:
  apt:
    packages:
      - clang-3.6
      - lcov

branches:
  only:
    - master

before_install:
  - pip install --user cpp-coveralls

script:
  - sh ./build-deps.sh
  - sh ./autogen.sh
  - ./configure --enable-gcov
  - make
  - make check

after_success:
  # Collect coverage and push to coveralls
  # Ignore third party source code and tests.
  - if [[ "$CC" == "gcc" && "$CODE_COVERAGE" == "ON" ]]; then
      coveralls
        --root ../
        --build-root ./
        --exclude-pattern '.+/lib/'
        --exclude-pattern '.+/test/'
        --gcov /usr/bin/gcov
        --gcov-options '\--long-file-names --preserve-paths'
        --verbose;
    fi
